Repository wecode-bootcamp-korea/27-1st-weasley-frontend, pull requests merged in 2021-12, with the labels that each got.

#2 [27기 황주영]상품상세페이지 구현
  public/data/detailcontents.json
  public/images/logo/logo-bk.svg
  public/images/logo/logo-mint.png
  public/images/logo/logo-white.svg
  public/images/productdetail/cleanser.png
  public/images/productdetail/cleanser_sensitive_1.47732c05.png
  public/images/productdetail/cleanser_sensitive_2.3508a10f.png
  public/images/productimage/cleanser2.png
  src/Router.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.md
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductDetailContents.js
  src/pages/ProductDetail/ProductDetailContents.scss
  src/pages/ProductDetail/ProductTop.js
  src/pages/ProductDetail/ProductTop.scss
  src/styles/common.scss
  src/styles/variables.scss
Labels: Status: Accepted

#6 [27기 황주영] 상품상세페이지 variables.scss 변수 재설정
  src/pages/ProductDetail/ProductDetailContents.scss
  src/pages/ProductDetail/ProductTop.scss
Labels: Status: 리뷰 요청

#1 [27기 황성재]상품리스트 페이지 수정완료
  public/data/1.md
  public/data/cartData1.json
  public/data/categoriesData.json
  public/images/ample1.png
  public/images/ample2.png
  public/images/ample3.png
  public/images/cleanser1.png
  public/images/cleanser2.png
  public/images/cleanser3.png
  public/images/lotion1.png
  public/images/lotion2.png
  public/images/lotion3.png
  public/images/moodimage1.png
  public/images/suncream1.png
  public/images/suncream2.png
  public/images/suncream3.png
  src/Router.js
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductListBanner/ProductListBanner.js
  src/pages/ProductList/ProductListBanner/ProductListBanner.scss
  src/pages/ProductList/ProductListHeader/ProductListHeader.js
  src/pages/ProductList/ProductListHeader/ProductListHeader.scss
  src/pages/ProductList/ProductListTitle/ProductListTitle.js
  src/pages/ProductList/ProductListTitle/ProductListTitle.scss
Labels: Status: Accepted

#4 [27기 황주영] 결제페이지 레이아웃, 기능구현완료
  public/data/payment/payinfo.json
  public/data/payment/userinfo.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/payment/GuestUserInfo.js
  src/pages/payment/GuestUserInfo.scss
  src/pages/payment/PayInfo.js
  src/pages/payment/PayInfo.scss
  src/pages/payment/Payment.js
  src/pages/payment/Payment.scss
  src/pages/payment/PaymentUserInfo.js
  src/pages/payment/PaymentUserInfo.scss
Labels: Status: 도움 요청, Status: Accepted

#12 [27기 김유량] nav 레이아웃 배치 새로 수정했습니다. 머지 부탁드립니다.
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#11 [27기 김유량] 로그인 버튼 활성화 수정했습니다. 컨플릭트 해결
  src/components/Nav.scss
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#15 [27기 김유량] 수정한 nav layout newnav branch 만들어서 PR 드립니다.
  src/Router.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#13 [27기 황성재]productlist페이지 variables.scss적용
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductListBanner/ProductListBanner.scss
  src/pages/ProductList/ProductListTitle/ProductListTitle.scss
Labels: Status: 리뷰 요청

#16 [27기 황성재]cart페이지 전체삭제 추가, api 주소변경, variables.scss 적용
  src/pages/Cart/.Cart.js.swp
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/EmptyCart.js
  src/pages/Cart/EmptyCart.scss
  src/pages/Cart/List.js
  src/pages/Cart/List.scss
  src/pages/Cart/Price.scss
  src/pages/ProductDetail/ProductDetailContents.scss
Labels: Status: 리뷰 요청

#18 [27기 황주영] main page 레이아웃 완료
  public/images/logo/logo-white.png
  public/index.html
  src/Router.js
  src/assets/images/mainbottomimg.png
  src/assets/images/maintopimg.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/ProductList/Product/Product.js
Labels: Status: 리뷰 요청

#9 [27기 김유량] 회원가입 페이지 레이아웃 구성 및 기능 구현
  public/index.html
  pull_request_template.md
  src/Router.js
  src/assets/images/signupbgi.jpg
  src/components/Nav.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/Login/Login.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/UserData.js
Labels: Status: 리뷰 요청

#19 [27 황주영] footerPage layout 추가
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
Labels: Status: 리뷰 요청

#8 [27기 황성재]구독 및 배송주기 관리 페이지 구현
  public/data/subscribeData.json
  public/data/subscribeProductData.json
  src/Router.js
  src/config.js
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/Subscribe/.Subscribe.js.swo
  src/pages/Subscribe/Subscribe.js
  src/pages/Subscribe/Subscribe.scss
  src/pages/Subscribe/SubscribeCycle.js
  src/pages/Subscribe/SubscribeCycle.scss
  src/pages/Subscribe/SubscribeProduct.js
  src/pages/Subscribe/SubscribeProduct.scss
  src/pages/Subscribe/SubscribeShipping.js
  src/pages/Subscribe/SubscribeShipping.scss
  src/pages/Subscribe/SubscribeUserBox.js
  src/pages/Subscribe/SubscribeUserBox.scss
Labels: Status: 리뷰 요청

#24 [27기 김유량] new branch feature/finalnav , conflict solved
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cart/.Cart.js.swp
Labels: Status: 리뷰 요청

#25 [27기 황성재]cart페이지에 link추가 및 포인터추가, margin-bottom추가
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/List.scss
Labels: Status: 리뷰 요청

#26 [27기황성재]상품리스트페이지 백엔드와 통신 및 제품이름 형식 변경
  src/config.js
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductListBanner/ProductListBanner.js
Labels: Status: Accepted

#27 [27기 김유량] Modify finalnav's brach layout
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#23 [27기 황성재]핵심성분페이지 구현
  public/data/ingredientData.json
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Ingredient/Ingredient.js
  src/pages/Ingredient/Ingredient.scss
  src/pages/Ingredient/IngredientList.js
  src/pages/Ingredient/IngredientList.scss
  src/pages/Ingredient/IngredientTitle.js
  src/pages/Ingredient/IngredientTitle.scss
Labels: Status: 리뷰 요청

#30 [27기 황성재]구독관리페이지 get요청 통신 및 데이터형식 변경
  src/config.js
  src/pages/Subscribe/Subscribe.js
  src/pages/Subscribe/SubscribeCycle.js
  src/pages/Subscribe/SubscribeProduct.js
  src/pages/Subscribe/SubscribeProduct.scss
  src/pages/Subscribe/SubscribeUserBox.js
Labels: Status: 리뷰 요청

#33 [27기 황성재]구독관리페이지 patch통신(배송주기변경)
  src/pages/Subscribe/SubscribeCycle.js
Labels: Status: 리뷰 요청

#34 [27기 황성재]정기배송주기 state변경
  src/pages/Subscribe/SubscribeCycle.js
Labels: Status: 리뷰 요청

#31 [27기 김유량] Add: logout 기능 추가 컨플릭트 해결
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/SignIn/SignIn.js
  src/pages/SignIn/SignIn.scss
Labels: Status: 리뷰 요청

#36 [27기 황성재]구독관리페이지 제품 레이아웃수정
  src/pages/Subscribe/SubscribeProduct.scss
Labels: Status: 리뷰 요청

#35 [27기 황주영] 상품상세페이지 구독페치 기능 추가
  public/data/productDetail/detailcontents.json
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductTop.js
  src/pages/ProductDetail/ProductTop.scss
Labels: Status: 리뷰 요청

#37 [27기 황성재]구독관리페이지 navigate추가
  src/pages/Subscribe/Subscribe.js
Labels: Status: 리뷰 요청

#39 [27기 황성재]토큰관리 및 메세지에 따른 분기처리
  src/pages/Cart/Cart.js
  src/pages/Cart/List.js
  src/pages/ProductDetail/ProductTop.js
  src/pages/Subscribe/Subscribe.js
  src/pages/Subscribe/SubscribeCycle.js
  src/pages/Subscribe/SubscribeProduct.js
  src/pages/payment/GuestUserInfo.js
  src/pages/payment/Payment.js
Labels: Status: 리뷰 요청
